# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\AboutWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_About(object):
    def setupUi(self, About):
        About.setObjectName("About")
        About.resize(1000, 600)
        About.setMinimumSize(QtCore.QSize(1000, 600))
        About.setMaximumSize(QtCore.QSize(1000, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\icons/menu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        About.setWindowIcon(icon)
        About.setStyleSheet("background-color: #5d5c60;")
        self.AboutApplicationText = QtWidgets.QLabel(About)
        self.AboutApplicationText.setGeometry(QtCore.QRect(36, 200, 921, 381))
        self.AboutApplicationText.setStyleSheet("font-size:16px; color: white;")
        self.AboutApplicationText.setAlignment(QtCore.Qt.AlignCenter)
        self.AboutApplicationText.setObjectName("AboutApplicationText")
        self.verticalLayoutWidget = QtWidgets.QWidget(About)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(39, 20, 231, 141))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.OpenManageWindowButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.OpenManageWindowButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.OpenManageWindowButton.setStyleSheet("background-color: #557a95; border: none;color: white;padding: 5px;text-align: center;  text-decoration: none;  font-size: 14px;\n"
"outline: none;")
        self.OpenManageWindowButton.setObjectName("OpenManageWindowButton")
        self.verticalLayout.addWidget(self.OpenManageWindowButton)
        self.ReturnBackButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.ReturnBackButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ReturnBackButton.setStyleSheet("background-color: #557a95; border: none;color: white;padding: 5px;text-align: center;  text-decoration: none;  font-size: 14px;\n"
"outline: none;")
        self.ReturnBackButton.setObjectName("ReturnBackButton")
        self.verticalLayout.addWidget(self.ReturnBackButton)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(About)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(730, 20, 231, 141))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.OpenAboutApplication = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.OpenAboutApplication.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.OpenAboutApplication.setStyleSheet("background-color: #557a95; border: none;color: white;padding: 5px;text-align: center;  text-decoration: none;  font-size: 14px;\n"
"outline: none;")
        self.OpenAboutApplication.setObjectName("OpenAboutApplication")
        self.verticalLayout_2.addWidget(self.OpenAboutApplication)
        self.CloseMainWindowButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.CloseMainWindowButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.CloseMainWindowButton.setStyleSheet("background-color: #557a95; border: none;color: white;padding: 5px;text-align: center;  text-decoration: none;  font-size: 14px;\n"
"outline: none;")
        self.CloseMainWindowButton.setObjectName("CloseMainWindowButton")
        self.verticalLayout_2.addWidget(self.CloseMainWindowButton)

        self.retranslateUi(About)
        QtCore.QMetaObject.connectSlotsByName(About)

    def retranslateUi(self, About):
        _translate = QtCore.QCoreApplication.translate
        About.setWindowTitle(_translate("About", "Главное меню"))
        self.AboutApplicationText.setText(_translate("About", "<html><head/><body><p>О программе:</p><p>Разработка и администрирование баз данных </p><p>Разработчик: студент группы МП-31 Бобков Данила</p></body></html>"))
        self.OpenManageWindowButton.setText(_translate("About", "Управление магазином"))
        self.ReturnBackButton.setText(_translate("About", "Назад"))
        self.OpenAboutApplication.setText(_translate("About", "О программе"))
        self.CloseMainWindowButton.setText(_translate("About", "Выйти"))
