# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\LogInWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys, os, os.path

class Ui_LogIn(object):
    def setupUi(self, LogIn):
        LogIn.setObjectName("LogIn")
        LogIn.resize(1000, 600)
        LogIn.setMinimumSize(QtCore.QSize(1000, 600))
        LogIn.setMaximumSize(QtCore.QSize(1000, 600))
        icondir = ""
        if hasattr(sys, "_MEIPASS"): icondir = os.path.join(sys._MEIPASS, './icons/login.png')
        else: icondir = './UserInterface/icons/login.png'
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(icondir), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        LogIn.setWindowIcon(icon)
        LogIn.setStyleSheet("background-color: #5d5c60;")
        self.formLayoutWidget = QtWidgets.QWidget(LogIn)
        self.formLayoutWidget.setGeometry(QtCore.QRect(340, 170, 321, 201))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setStyleSheet(" font-size: 14px; color:white;")
        self.label.setObjectName("label")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setStyleSheet(" font-size: 14px; color:white;")
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.LogInButton = QtWidgets.QPushButton(self.formLayoutWidget)
        self.LogInButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.LogInButton.setStyleSheet("background-color: #7395ae;  border: none;  color: white;  padding: 5px;  text-align: center; text-decoration: none;  font-size: 14px;\n"
"outline: none;")
        self.LogInButton.setObjectName("LogInButton")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.LogInButton)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(5, QtWidgets.QFormLayout.FieldRole, spacerItem)
        self.UsernameLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.UsernameLineEdit.setStyleSheet("color: white;")
        self.UsernameLineEdit.setObjectName("UsernameLineEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.UsernameLineEdit)
        self.PasswordLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.PasswordLineEdit.setStyleSheet("color: white;")
        self.PasswordLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.PasswordLineEdit.setObjectName("PasswordLineEdit")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.PasswordLineEdit)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(7, QtWidgets.QFormLayout.FieldRole, spacerItem1)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setStyleSheet(" font-size: 16px; color:white;")
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.label_3)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(3, QtWidgets.QFormLayout.FieldRole, spacerItem2)

        self.retranslateUi(LogIn)
        QtCore.QMetaObject.connectSlotsByName(LogIn)

    def retranslateUi(self, LogIn):
        _translate = QtCore.QCoreApplication.translate
        LogIn.setWindowTitle(_translate("LogIn", "Авторизация"))
        self.label.setText(_translate("LogIn", "Имя пользователя:"))
        self.label_2.setText(_translate("LogIn", "Пароль:"))
        self.LogInButton.setText(_translate("LogIn", "Войти"))
        self.label_3.setText(_translate("LogIn", "Введите данные от аккаунта:"))
