# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ReportWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys, os, os.path

class Ui_Report(object):
    def setupUi(self, Report):
        Report.setObjectName("Report")
        Report.resize(1000, 600)
        Report.setMinimumSize(QtCore.QSize(1000, 600))
        Report.setMaximumSize(QtCore.QSize(1000, 600))
        icondir = ""
        if hasattr(sys, "_MEIPASS"): icondir = os.path.join(sys._MEIPASS, './icons/report.png')
        else: icondir = './UserInterface/icons/report.png'
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(icondir), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Report.setWindowIcon(icon)
        Report.setStyleSheet("background-color: #5d5c60;")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Report)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 10, 401, 91))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setStyleSheet("font-size: 14px; color: white;")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.TableNameComboBox = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.TableNameComboBox.setEnabled(True)
        self.TableNameComboBox.setStyleSheet("border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"  padding: 6px; color: white;")
        self.TableNameComboBox.setObjectName("TableNameComboBox")
        self.TableNameComboBox.addItem("")
        self.TableNameComboBox.addItem("")
        self.TableNameComboBox.addItem("")
        self.TableNameComboBox.addItem("")
        self.TableNameComboBox.addItem("")
        self.horizontalLayout.addWidget(self.TableNameComboBox)
        self.AddNewReportButton = QtWidgets.QPushButton(Report)
        self.AddNewReportButton.setEnabled(True)
        self.AddNewReportButton.setGeometry(QtCore.QRect(20, 110, 158, 27))
        self.AddNewReportButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.AddNewReportButton.setStyleSheet("background-color: #557a95;\n"
"border: none;\n"
"color: white;\n"
"padding: 5px;\n"
"text-align: center;\n"
"text-decoration: none;\n"
"font-size: 14px;\n"
"outline: none;")
        self.AddNewReportButton.setObjectName("AddNewReportButton")
        self.scrollArea = QtWidgets.QScrollArea(Report)
        self.scrollArea.setGeometry(QtCore.QRect(20, 160, 961, 431))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 959, 429))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.ListOfReportWidget = QtWidgets.QListWidget(self.scrollAreaWidgetContents)
        self.ListOfReportWidget.setGeometry(QtCore.QRect(0, 0, 961, 431))
        self.ListOfReportWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.ListOfReportWidget.setStyleSheet("color: white;")
        self.ListOfReportWidget.setObjectName("ListOfReportWidget")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.SpecialReportsCheckBox = QtWidgets.QCheckBox(Report)
        self.SpecialReportsCheckBox.setGeometry(QtCore.QRect(280, 110, 131, 21))
        self.SpecialReportsCheckBox.setStyleSheet("color: white;")
        self.SpecialReportsCheckBox.setObjectName("SpecialReportsCheckBox")
        self.ReturnBackButton = QtWidgets.QPushButton(Report)
        self.ReturnBackButton.setEnabled(True)
        self.ReturnBackButton.setGeometry(QtCore.QRect(820, 110, 158, 27))
        self.ReturnBackButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ReturnBackButton.setStyleSheet("background-color: #557a95; border: none;color: white;padding: 5px;text-align: center;  text-decoration: none;  font-size: 14px;\n"
"outline: none;")
        self.ReturnBackButton.setObjectName("ReturnBackButton")
        self.FilterNameComboBox = QtWidgets.QComboBox(Report)
        self.FilterNameComboBox.setEnabled(True)
        self.FilterNameComboBox.setGeometry(QtCore.QRect(430, 40, 196, 32))
        self.FilterNameComboBox.setStyleSheet("border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"  padding: 6px; color: white;")
        self.FilterNameComboBox.setObjectName("FilterNameComboBox")

        self.retranslateUi(Report)
        self.TableNameComboBox.setCurrentIndex(0)
        self.FilterNameComboBox.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(Report)

    def retranslateUi(self, Report):
        _translate = QtCore.QCoreApplication.translate
        Report.setWindowTitle(_translate("Report", "Отчет"))
        self.label.setText(_translate("Report", "Выберете отчет"))
        self.TableNameComboBox.setItemText(0, _translate("Report", "Клиенты"))
        self.TableNameComboBox.setItemText(1, _translate("Report", "Заказы"))
        self.TableNameComboBox.setItemText(2, _translate("Report", "Товары"))
        self.TableNameComboBox.setItemText(3, _translate("Report", "Сотрудники"))
        self.TableNameComboBox.setItemText(4, _translate("Report", "Должности"))
        self.AddNewReportButton.setText(_translate("Report", "Подтвердить"))
        self.ListOfReportWidget.setSortingEnabled(False)
        self.SpecialReportsCheckBox.setText(_translate("Report", "Специальные отчеты"))
        self.ReturnBackButton.setText(_translate("Report", "Назад"))
