# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\TapeWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys, os, os.path

class Ui_Tape(object):
    def setupUi(self, Tape):
        Tape.setObjectName("Tape")
        Tape.setEnabled(True)
        Tape.resize(400, 513)
        Tape.setMinimumSize(QtCore.QSize(400, 500))
        Tape.setMaximumSize(QtCore.QSize(400, 800))
        Tape.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        icondir = ""
        if hasattr(sys, "_MEIPASS"): icondir = os.path.join(sys._MEIPASS, './icons/ribbon.png')
        else: icondir = './UserInterface/icons/ribbon.png'
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(icondir), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Tape.setWindowIcon(icon)
        Tape.setStyleSheet("background-color: #5d5c60;")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Tape)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 440, 341, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.PreviousRecordButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.PreviousRecordButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.PreviousRecordButton.setStyleSheet("background-color: #557a95;\n"
"border: none;\n"
"color: white;\n"
"padding: 5px;\n"
"text-align: center;\n"
"text-decoration: none;\n"
"font-size: 14px;\n"
"outline: none;")
        self.PreviousRecordButton.setObjectName("PreviousRecordButton")
        self.horizontalLayout.addWidget(self.PreviousRecordButton)
        self.NextRecordButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.NextRecordButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.NextRecordButton.setStyleSheet("background-color: #557a95;\n"
"border: none;\n"
"color: white;\n"
"padding: 5px;\n"
"text-align: center;\n"
"text-decoration: none;\n"
"font-size: 14px;\n"
"outline: none;")
        self.NextRecordButton.setObjectName("NextRecordButton")
        self.horizontalLayout.addWidget(self.NextRecordButton)
        self.verticalLayoutWidget = QtWidgets.QWidget(Tape)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 10, 341, 411))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.MainTapeLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.MainTapeLayout.setContentsMargins(0, 0, 0, 0)
        self.MainTapeLayout.setObjectName("MainTapeLayout")

        self.retranslateUi(Tape)
        QtCore.QMetaObject.connectSlotsByName(Tape)

    def retranslateUi(self, Tape):
        _translate = QtCore.QCoreApplication.translate
        Tape.setWindowTitle(_translate("Tape", "Ленточная форма"))
        self.PreviousRecordButton.setText(_translate("Tape", "Назад"))
        self.NextRecordButton.setText(_translate("Tape", "Вперед"))
